[[features]]
title = ""
description = ""

[[breaking]]
title = "Enums"
description = "All 'enum' collection variables have been changed. The word 'Collection' has been appended to all variable names. [#223](https://github.com/oxidecomputer/oxide.go/pull/223)"

[[breaking]]
title = "Instances"
description = "The migration endpoint has been removed. [#223](https://github.com/oxidecomputer/oxide.go/pull/223)"

[[enhancements]]
title = "Metrics"
description = "The 'TimeseriesSchema' type now has additional fields. [#223](https://github.com/oxidecomputer/oxide.go/pull/223)"

[[bugs]]
title = ""
description = ""