[[breaking]]
title = ""
description = ""

[[features]]
title = ""
description = ""

[[bugs]]
title = "Fixed path element escaping"
description = "Path elements were being escaped using the character set for query params. [#439](https://github.com/oxidecomputer/oxide.go/pull/439)"

[[enhancements]]
title = ""
description = ""
