[[breaking]]
title = ""
description = ""

[[features]]
title = ""
description = ""

[[bugs]]
title = ""
description = ""

[[enhancements]]
title = "Update Go version"
description = "The SDK's version has been updated to 1.22"