[[breaking]]
title = ""
description = ""

[[features]]
title = ""
description = ""

[[bugs]]
title = ""
description = ""

[[enhancements]]
title = "Prevent mutations to input client"
description = "`NewClient` options now clone inputs to prevent mutations to inputs. [#441](https://github.com/oxidecomputer/oxide.go/pull/441)"
