[[breaking]]
title = ""
description = ""

[[features]]
title = ""
description = ""

[[bugs]]
title = ""
description = ""

[[enhancements]]
title = "Update Go version"
description = "The SDK's version has been updated to 1.22. [243](https://github.com/oxidecomputer/oxide.go/pull/243)"