[[breaking]]
title = ""
description = ""

[[features]]
title = ""
description = ""

[[bugs]]
title = "Fix `NewIpNet` parsing"
description = "Fixed a bug that could cause invalid strings to be accepted as valid NetIpNet values. [#440](https://github.com/oxidecomputer/oxide.go/pull/440)"

[[enhancements]]
title = ""
description = ""
