[[features]]
title = "New API endpoints"
description = "Floating IP update, IP pool utilization view, physical disk view, timeseries query, timeseries schema list, and BGP message history. [#195](https://github.com/oxidecomputer/oxide.go/pull/195), [#201](https://github.com/oxidecomputer/oxide.go/pull/201), [#202](https://github.com/oxidecomputer/oxide.go/pull/202)"

[[enhancements]]
title = "Documentation"
description = "Go doc comments now include which fields are required for each type. [#198](https://github.com/oxidecomputer/oxide.go/pull/198)"
