[[breaking]]
title = ""
description = ""

[[features]]
title = "Switch Port LLDP Neighbors"
description = "CRUD functionality for LLDP neighbors seen on a switch port. [#XXX](https://github.com/oxidecomputer/oxide.go/pull/XXX)"

[[bugs]]
title = ""
description = ""

[[enhancements]]
title = ""
description = ""