[[breaking]]
title = ""
description = ""

[[features]]
title = "Affinity and anti-affinity groups"
description = "CRUD methods. [#XXX](https://github.com/oxidecomputer/oxide.go/pull/XXX)"

[[bugs]]
title = ""
description = ""

[[enhancements]]
title = ""
description = ""