// Code generated by `generate`. DO NOT EDIT.

// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

package oxide

// version is the Oxide Go SDK version. This is used to dynamically populate the
// user agent for [Client].
const version = "v0.12.0"

// APIVersion is the OpenAPI specification version the Oxide Go SDK was
// generated from. This is used to populate the 'API-Version' header for
// [Client].
const APIVersion = "2026073100.0.0"
