// Code generated by `generate`. DO NOT EDIT.

// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

package oxide

// sdkVersion is the Oxide Go SDK sdkVersion. This is used to dynamically
// populate the user agent for [Client]. It is purposefully unexported to
// prevent external users from reading it. The value of this comes from the
// VERSION file in the root of this repository.
const sdkVersion = "v0.8.0"

// openAPIVersion is the OpenAPI specification version the Oxide Go SDK was
// generated from. This is used to dynamically populate the 'API-Version' header
// for [Client]. It is purposefully unexported to prevent external users from
// reading it. The value of this comes from the OpenAPI specification associated
// with the OMICRON_VERSION file in the root of this repository.
const openAPIVersion = "2025120300.0.0"
